-- Corre esto en el SQL Editor de Supabase (proyecto Howria)

create table if not exists boletas_adiestramiento (
  id uuid primary key default gen_random_uuid(),
  numero int generated by default as identity,
  cliente_id uuid references clientes(id) on delete set null,
  cliente_nombre text not null,
  perro text,
  modalidad text not null default 'individual' check (modalidad in ('individual', 'grupal')),
  num_clases int not null default 1,
  precio_clase numeric not null default 0,
  descuento_pack_pct numeric not null default 0,
  evaluacion text not null default 'ninguna' check (evaluacion in ('ninguna', 'presencial', 'online')),
  precio_evaluacion numeric not null default 0,
  transporte numeric not null default 0,
  total numeric not null default 0,
  mensaje_personalizado text,
  estado text not null default 'no_enviada' check (estado in ('no_enviada', 'pendiente_pago', 'pagada', 'cancelada')),
  fecha_hora timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table boletas_adiestramiento enable row level security;
create policy "solo_autenticados" on boletas_adiestramiento for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Que los adiestradores (rol entrenador) también vean esta pestaña nueva
update permisos_roles set tabs = array_append(tabs, 'boletas-adiestramiento')
where rol in ('entrenador', 'coordinador', 'administrador')
  and not ('boletas-adiestramiento' = any(tabs));
