-- Ya corrido en el SQL Editor de Supabase (proyecto Howria) el 2026-08-14.
-- Se deja acá solo como registro histórico — no hace falta volver a
-- correrlo.
--
-- Contexto: numero_boleta_unico.sql (mismo día) detectó números de
-- boleta repetidos ya existentes en producción — la app calculaba el
-- próximo número leyendo el máximo actual y sumando 1 en el navegador,
-- así que dos sesiones generando una boleta casi al mismo tiempo podían
-- calcular el mismo número. Se investigó con el dueño del negocio y se
-- decidió: (1) borrar todas las boletas existentes (de paseo y de
-- adiestramiento, con boletas ya pagadas y pendientes de por medio —
-- se exportó un respaldo CSV de ambas tablas antes de borrar), y (2)
-- que la base de datos asigne el número ella sola de ahora en más, para
-- que nunca más pueda haber un choque.
--
-- alter column ... set generated always: ahora Postgres asigna "numero"
-- siempre, y rechaza cualquier insert que intente mandar un valor propio
-- (antes era "generated by default", que permitía a la app mandar el
-- suyo — ver ajuste_numero_boleta.sql). El código de HowriaAdmin.jsx
-- (Boletas.generar() / BoletasAdiestramiento.generar()) ya no manda
-- "numero" al crear una boleta — lo lee de vuelta desde la fila que
-- Supabase devuelve después del insert.
--
-- restart with 2200: para que el primer número visible después de este
-- cambio sea uno fácil de reconocer, bien por delante de cualquier
-- número usado antes.

delete from boletas;
delete from boletas_adiestramiento;

alter table boletas alter column numero set generated always;
alter table boletas alter column numero restart with 2200;

alter table boletas_adiestramiento alter column numero set generated always;
alter table boletas_adiestramiento alter column numero restart with 2200;
