-- Corre esto en el SQL Editor de Supabase (proyecto Howria)
--
-- Chat interno del equipo: un solo canal compartido entre todo el staff
-- (paseador, entrenador, coordinador, administrador) — no clientes/tutores.
-- Sin edición ni borrado de mensajes por ahora, solo escribir y leer.
-- El "no leídos" del icono del chat sale de mensajes_equipo_lecturas
-- (089_mensajes_equipo_lecturas.sql), no de esta tabla.

create table if not exists mensajes_equipo (
  id bigint generated by default as identity primary key,
  autor_email text not null,
  autor_nombre text not null,
  texto text not null,
  creado_en timestamptz not null default now()
);

create index if not exists mensajes_equipo_creado_en_idx on mensajes_equipo (creado_en);

alter table mensajes_equipo enable row level security;

-- mi_rol() (definida en 019_rls_permisos_por_rol.sql) devuelve null para
-- cuentas que no están en "usuarios" (ej. el portal de un cliente/tutor) —
-- así el chat queda acotado al staff sin tener que enumerar los 4 roles.
drop policy if exists "mensajes_equipo_select_staff" on mensajes_equipo;
create policy "mensajes_equipo_select_staff" on mensajes_equipo for select using (mi_rol() is not null);

drop policy if exists "mensajes_equipo_insert_propio" on mensajes_equipo;
create policy "mensajes_equipo_insert_propio" on mensajes_equipo for insert with check (
  mi_rol() is not null and autor_email = (auth.jwt() ->> 'email')
);

-- Sin esto los mensajes nuevos no llegan solos — hay que agregar la tabla
-- a la publicación de Supabase a mano (mismo criterio que
-- 046_realtime_paseos_agenda_correos.sql / 049_fase_dia_paseador.sql).
alter publication supabase_realtime add table mensajes_equipo;
