-- Corre esto en el SQL Editor de Supabase (proyecto Howria)
--
-- Inventario del coordinador: registro de qué equipo (collares, correas,
-- poleras, polerones, accesorios) se le ha entregado a cada paseador o
-- entrenador — con fecha, así se puede ver el historial completo, no
-- solo el total actual. Sin stock central de bodega por ahora (decisión
-- explícita de Javier) — solo lo que ya salió hacia cada persona.

create table if not exists entregas_inventario (
  id bigint generated by default as identity primary key,
  paseador_nombre text not null,
  articulo text not null,
  talla text,
  descripcion text,
  cantidad integer not null default 1,
  entregado_por text not null,
  entregado_en timestamptz not null default now()
);

create index if not exists entregas_inventario_paseador_idx on entregas_inventario (paseador_nombre);

alter table entregas_inventario enable row level security;

-- Solo coordinación/administración lo ven y lo escriben — es un panel de
-- coordinación, no algo que un paseador reporte sobre sí mismo.
drop policy if exists "entregas_inventario_select_coord_admin" on entregas_inventario;
create policy "entregas_inventario_select_coord_admin" on entregas_inventario for select using (mi_rol() in ('coordinador', 'administrador'));

drop policy if exists "entregas_inventario_insert_coord_admin" on entregas_inventario;
create policy "entregas_inventario_insert_coord_admin" on entregas_inventario for insert with check (mi_rol() in ('coordinador', 'administrador'));

drop policy if exists "entregas_inventario_delete_coord_admin" on entregas_inventario;
create policy "entregas_inventario_delete_coord_admin" on entregas_inventario for delete using (mi_rol() in ('coordinador', 'administrador'));
