-- Corre esto en el SQL Editor de Supabase (proyecto Howria)
--
-- Mover un paseo puntual de un día a otro (ej. el cliente no pudo el
-- lunes y quiere dejarlo para el martes) — sin tocar clientes.dias_habituales
-- (sigue siendo el horario normal de siempre) y sin afectar la meta/pago
-- del paseador (el paseo igual cuenta como hecho, solo que en otra fecha
-- — ver estaProgramadoEnFecha en HowriaAdmin.jsx, que ahora consideran
-- todos los lugares que antes solo miraban dias_habituales).

create table if not exists paseos_reprogramados (
  id bigint generated by default as identity primary key,
  cliente_id uuid not null references clientes(id) on delete cascade,
  fecha_origen date not null,
  fecha_nueva date not null,
  paseador_nombre text not null,
  motivo text,
  creado_por text not null,
  creado_en timestamptz not null default now()
);

create index if not exists paseos_reprogramados_cliente_idx on paseos_reprogramados (cliente_id);
create index if not exists paseos_reprogramados_fecha_nueva_idx on paseos_reprogramados (fecha_nueva);

alter table paseos_reprogramados enable row level security;

-- Coordinación/administración las crean y gestionan. El paseador afectado
-- también necesita leer las suyas — a diferencia de Inventario, acá sí es
-- un consumidor real de la información (tiene que saber que ahora le
-- toca pasear a Venom el martes).
drop policy if exists "paseos_reprogramados_select" on paseos_reprogramados;
create policy "paseos_reprogramados_select" on paseos_reprogramados for select using (
  mi_rol() in ('coordinador', 'administrador') or paseador_nombre = mi_nombre()
);

drop policy if exists "paseos_reprogramados_insert_coord_admin" on paseos_reprogramados;
create policy "paseos_reprogramados_insert_coord_admin" on paseos_reprogramados for insert with check (mi_rol() in ('coordinador', 'administrador'));

drop policy if exists "paseos_reprogramados_delete_coord_admin" on paseos_reprogramados;
create policy "paseos_reprogramados_delete_coord_admin" on paseos_reprogramados for delete using (mi_rol() in ('coordinador', 'administrador'));

-- El paseador tiene que enterarse al toque si la app le queda abierta —
-- mismo criterio que citas_agenda/registro_paseos/fase_dia_paseador.
alter publication supabase_realtime add table paseos_reprogramados;
