-- Corre esto en el SQL Editor de Supabase (proyecto Howria),
-- DESPUÉS de haber corrido schema_howria.sql.
--
-- Por qué: la tabla "boletas" generaba el número automáticamente,
-- pero la app arma el número (N°108, N°109...) ella misma antes de
-- guardar, así que necesitamos permitir que la app indique el número.

alter table boletas alter column numero set generated by default;
